# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 03:58
from __future__ import unicode_literals

import Store.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=12)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
            ],
            options={
                'verbose_name': 'Opening Hour',
                'verbose_name_plural': 'Opening Hours',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=Store.models.token_generator, editable=False, max_length=20, unique=True)),
                ('name_of_product', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=Store.models.token_generator, editable=False, max_length=20, unique=True)),
                ('name_of_legal_entity', models.CharField(max_length=250)),
                ('pan_number', models.CharField(max_length=20)),
                ('registered_office_address', models.CharField(max_length=200)),
                ('name_of_store', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('store_contact_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_category', models.CharField(choices=[('GROCERY', 'Grocery'), ('MEATS', 'Meats'), ('FOODS & BEVERAGES', 'Foods'), ('COMPUTERS', 'Computers'), ('ELECTRONICS', 'Electronics'), ('HOME & OUTDOOR', 'Home & Outdoor'), ('FASHION & BEAUTY', 'Fashion & Beauty'), ('HEALTH', 'Health'), ('SPORTS & FITNESS', 'Sports & Fitness'), ('BABY', 'Baby'), ('BOOKS', 'Books')], default='GROCERY', max_length=30)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.Product')),
            ],
            options={
                'verbose_name': 'Store Category',
                'verbose_name_plural': 'Store Categories',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='store_categories',
            field=models.ManyToManyField(blank=True, to='Store.StoreCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.ProductImage'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store'),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Store'),
        ),
    ]
