# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_categories',
        ),
    ]
