# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_store_store_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='merchant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
